#! /usr/bin/env python

import sys
import Utils

## Build world daemon as standalone program

mangos_worldd_src = [
	'CliRunnable.cpp',
	'Main.cpp',
	'Master.cpp',
	'RASocket.cpp',
	'MaNGOSsoap.cpp',
	'WorldRunnable.cpp',
	'soapC.cpp',
	'soapServer.cpp' ]

mangos_worldd_lib = [
#	'mangosscript',
	'mangosgame',
	'mangosdatabase',
	'mangosconfig',
	'mangosauth',
	'mangosshared',
	'mangosvmaps',
	'mangosframework',
	'mangosscript', # linking required because unload not safe...
	'g3dlite',
	'gsoap',
	'ACE',
	'MYSQL',
	'LIBSSL' ]
	
mangos_worldd_inc = [
	'../..',
	'../shared',
	'../framework',
	'../game',
	'../../dep/include',
	'../../dep/include/gsoap' ]

mangos_worldd = bld.program(source = mangos_worldd_src,
	includes = mangos_worldd_inc,
	use = mangos_worldd_lib,
	install_path = '${PREFIX}/mangos/bin',
	target = 'mangos-worldd')

if sys.platform != 'win32':
	mangos_worldd.rpath = Utils.subst_vars('${PREFIX}/mangos/lib', bld.env)

#bld.add_manual_dependency(
#	'mangos-worldd',
#	bld.path.find_node('revision.h'))

bld.install_as('${PREFIX}/mangos/etc/mangosd.conf.dist', 'mangosd.conf.dist.in')

