#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
	mpq_env = conf.env.derive()
	conf.set_env_name('mpq', mpq_env)
	conf.setenv('mpq')
	conf.define('VERSION', '0.4.2')
	conf.write_config_header('config.h')

	# restore default, just to be sure...
	conf.setenv('default')
