#! /usr/bin/env python

libmangosshared_src = [
	'Common.cpp',
	'Log.cpp',
	'MemoryLeaks.cpp',
	'ProgressBar.cpp',
	'Threading.cpp',
	'Util.cpp',
	'Config/Config.cpp']

libmangosshared_inc = ['.', '../..', '../framework', '../../dep/include', '../../dep/include/g3dlite']
	
lib = bld.stlib(source = libmangosshared_src,
	includes = libmangosshared_inc,
	use = ['ACE'],
	install_path = None,
	target = 'mangosshared')

# explicitly make mangosshared lib depend on revision.h created from genrevision
bld.add_manual_dependency(
	'mangosshared',
	bld.path.find_node('revision.h'))

bld.recurse(['Auth', 'Database'])

