#! /usr/bin/env python

libmangosshared_src = [
	'Common.cpp',
	'Log.cpp',
	'MemoryLeaks.cpp',
	'ProgressBar.cpp',
	'Threading.cpp',
	'Util.cpp']

libmangosshared_inc = ['.', '../framework', '../../dep/include', '../../dep/include/g3dlite']
	
lib = bld.stlib(source = libmangosshared_src,
	includes = libmangosshared_inc,
	target = 'mangosshared')

print(type(lib))
# explicitly make mangosshared lib depend on revision.h created from genrevision
bld.add_manual_dependency(
	'mangosshared',
	bld.path.find_node('revision.h'))
