#! /usr/bin/env python

mangosvmaps_src = [
	'BIH.cpp',
	'MapTree.cpp',
	'ModelInstance.cpp',
	'TileAssembler.cpp',
	'VMapFactory.cpp',
	'VMapManager2.cpp',
	'WorldModel.cpp' ]

mangosvmaps_inc = ['.', '..',
	'../../../',
	'../../framework',
	'../../shared',
	'../../../dep/include',
	'../../../dep/include/g3dlite' ]

bld.stlib(
	source = mangosvmaps_src,
	includes = mangosvmaps_inc,
	install_path = None,
	target = 'mangosvmaps')

if bld.env.WITH_TOOLS:
	bld.stlib(
		source = mangosvmaps_src,
		includes = mangosvmaps_inc,
		defines = bld.env.CONTRIB_DEFINES,
		install_path = None,
		target = 'mangosvmaps_ext')

